const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
// Directories to scan for gallery media
const scanDirs = ['Archive', 'Catalogo'];
const outPath = path.join(rootDir, 'assets', 'js', 'galleryData.js');

const imageExts = new Set(['.jpg', '.jpeg', '.png', '.gif', '.webp']);
const videoExts = new Set(['.mp4', '.webm', '.ogg']);

const galleryMedia = [];

function walkDir(currentPath, baseDir) {
  if (!fs.existsSync(currentPath)) return;
  const entries = fs.readdirSync(currentPath, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue; // skip hidden files

    const fullPath = path.join(currentPath, entry.name);
    // Path relative to the root website folder
    const relPath = path.relative(rootDir, fullPath).replace(/\\/g, '/');

    if (entry.isDirectory()) {
      walkDir(fullPath, baseDir);
    } else {
      const ext = path.extname(entry.name).toLowerCase();
      
      // Ensure the file is safe for web paths (encode it so the browser loads it correctly)
      const segments = relPath.split('/');
      const safePath = segments.map(seg => encodeURIComponent(seg)).join('/');
      
      if (imageExts.has(ext)) {
        galleryMedia.push({ src: safePath, type: 'image', filename: entry.name, directory: path.dirname(relPath) });
      } else if (videoExts.has(ext)) {
        galleryMedia.push({ src: safePath, type: 'video', filename: entry.name, directory: path.dirname(relPath) });
      }
    }
  }
}

scanDirs.forEach(dirName => {
  const target = path.join(rootDir, dirName);
  walkDir(target, dirName);
});

// Write output
const jsContent = `// Automatically generated by scripts/build-gallery.js\nwindow.aeGalleryData = ${JSON.stringify(galleryMedia, null, 2)};`;

fs.writeFileSync(outPath, jsContent, 'utf-8');
console.log(`Gallery rebuilt: ${galleryMedia.length} media files found.`);
